bot: 
  appID: '102012144' # 申请机器人时获取到的机器人 BotAppID
  token: 'CwrVvliKCv4ZRnW6GRF4qTJjvoJid6h8' # 申请机器人时获取到的机器人 BotToken
  # 事件订阅,用于开启可接收的消息类型GUILDS，PUBLIC_GUILD_MESSAGES，DIRECT_MESSAGE，GUILD_MEMBERS
  intents: ['PUBLIC_GUILD_MESSAGES', 'GUILD_MESSAGES', 'GUILD_MEMBERS ']
  sandbox: false # 沙箱支持，可选，默认false. v2.7.0+


#################### 申请 key ########################

#  https://wx.jdcloud.com/api/0_0/1
jd_api_key: "292e3c17f2ae5068c7ea5f15cb4ecd6c"